kind: pipeline
name: Drone ci

steps:
- name: unit test
  image: node
  commands:
  - npm install
  - npm run test:unit  
  when:
    branch:
    - develop
    event:
      - pull_request

- name: docker  
  image: plugins/docker
  settings:
    repo: naikyding/drone-ci
    username: 
        from_secret: docker_username
    password: 
        from_secret: docker_password
    tags: latest
  when:
    branch:
    - master
    event:
      - push

trigger:
  branch:
  - master
  - develop